# Use Ubuntu 22.04 as base image
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Update system
RUN apt-get update && apt-get upgrade -y

# Install required packages
RUN apt-get install -y \
    git \
    curl \
    wget \
    nano \
    vim \
    sudo \
    cron \
    software-properties-common \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-distutils \
    python3-venv \
    mariadb-server \
    mariadb-client \
    redis-server \
    xvfb \
    libfontconfig1 \
    wkhtmltopdf \
    libmysqlclient-dev \
    pkg-config \
    build-essential

# Install NodeJS 18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

# Install Yarn
RUN npm install -g yarn

# Install Frappe Bench
RUN pip3 install frappe-bench

# Create frappe user
RUN useradd -ms /bin/bash frappe

# Create home directory
RUN mkdir -p /home/frappe

# Give permissions
RUN chown -R frappe:frappe /home/frappe

# Switch to frappe user
USER frappe

WORKDIR /home/frappe

# Initialize Bench
RUN bench init --frappe-branch version-15 frappe-bench

WORKDIR /home/frappe/frappe-bench

# Expose ERPNext Port
EXPOSE 8000

# Start required services and ERPNext
CMD ["bench", "start"]